VIA_ENABLE = yes
RGB_MATRIX_ENABLE = yes
BOOTMAGIC_ENABLE = lite

IDLE_TIMEOUT_ENABLE = yes
STARTUP_NUMLOCK_ON = yes

DEBOUNCE_TYPE = asym_eager_defer_pk
USB_POLLING_INTERVAL_MS = 1
QMK_KEYS_PER_SCAN = 12
